### ISSUE TITLE
Raw Preview no longer working @ Nextcloud 17.0.1

### ISSUE THREAD

**Issue by aJanker** [ariselseng/camerarawpreviews#37]
After upgrading Nextcloud from 17.0.0 to 17.0.1 the camerarawpreviews app @ version 0.7.2 is no longer working and is failing with following exception:

```
[remote] Error: ArgumentCountError: Too few arguments to function OCA\CameraRawPreviews\RawPreviewBase::__construct(), 0 passed in /var/www/nc/apps/camerarawpreviews/appinfo/app.php on line 42 and exactly 2 expected at <<closure>>

 0. /var/www/nc/apps/camerarawpreviews/appinfo/app.php line 42
    OCA\CameraRawPreviews\RawPreviewBase->__construct()
 1. /var/www/nc/lib/private/Preview/GeneratorHelper.php line 77
    OC_App::{closure}("*** sensitive parameters replaced ***")
 2. /var/www/nc/lib/private/PreviewManager.php line 264
    OC\Preview\GeneratorHelper->getProvider(Closure {})
 3. /var/www/nc/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 356
    OC\PreviewManager->isAvailable(OC\Files\FileInfo {})
 4. /var/www/nc/3rdparty/sabre/dav/lib/DAV/PropFind.php line 98
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/nc/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 357
    Sabre\DAV\PropFind->handle("{http://nextcloud.org/ns}has-preview", Closure {})
 6. <<closure>>
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\File {})
 7. /var/www/nc/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\Connect ... "], [Sabre\DAV\PropF ... }])
 8. /var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
 9. /var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\Connector\Sabre\File {})
10. /var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/xxx/Pict ... W", ["{DAV:}getlastm ... "], 1)
11. /var/www/nc/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
12. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. /var/www/nc/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
14. /var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
15. /var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
16. /var/www/nc/apps/dav/lib/Server.php line 317
    Sabre\DAV\Server->exec()
17. /var/www/nc/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /var/www/nc/remote.php line 163
    undefinedundefinedrequire_once("/var/www/nc/app ... p")
```

PROPFIND /remote.php/dav/files/xxx/RAW
from xxx by xxx at 2019-11-11T19:52:55+00:00

**Comment by ariselseng** [comment]
@aJanker First question. Which php version do you have? I just tried with the 17.0.1rc1 docker image and that worked well.

**Comment by ariselseng** [comment]
Also, did you upgrade the camerarawpreviews recently? It could be some kind of cache problem. Do you use opcache or any other cache with nextcloud?

**Comment by aJanker** [comment]
yeah - my bad. a php-fpm service reload did the trick. thank you very much for your help and sorry for any inconvenice.

great work btw :)
